'use client'

import './globals.css'
import type { Metadata } from 'next'
import { Quicksand } from 'next/font/google'
import * as React from "react";
import { NextUIProvider } from "@nextui-org/react";
import { ComponentContextProvider } from './context/context'


const quicksand = Quicksand( { subsets: ['latin'] } )

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout ( {
  children,
}: {
  children: React.ReactNode
} )
{
  return (
    <html lang="en">
      <body className={`${quicksand.className} gradient-background`}>
        <NextUIProvider>
          <ComponentContextProvider>
            {children}
          </ComponentContextProvider>
        </NextUIProvider>
      </body>
    </html>
  )
}
