'use client'

import { ReactNode } from "react";
import Sidebar from "../Sidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
   title: 'Raffle Draw',
   description: 'Generated by create next app',
}

export default function RaffleLayout ( { children }: { children: ReactNode } )
{
   return (
      <main className={`flex min-h-screen`}>
         <Sidebar />

         {/* MAIN CONTENT */}
         {children}
      </main>
   )
}